In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('population.csv')
df.head()

        Entity Code   Year  Population (historical)
0  Afghanistan  AFG -10000                    14737
1  Afghanistan  AFG  -9000                    20405
2  Afghanistan  AFG  -8000                    28253
3  Afghanistan  AFG  -7000                    39120
4  Afghanistan  AFG  -6000                    54166

In [3]:
df = df[df['Entity'].isin(['Asia', 'Europe', 'Africa', 'Oceania', 'North America', 'South America'])]
df = df[(df['Year'] <= 2023) & (df['Year'] >= 1920)]
global_population = df.groupby("Year")["Population (historical)"].sum()

# Merge the computed global population back into the dataframe
df["Global Annual Population (billions)"] = df["Year"].map(global_population)
df = df[df['Entity'] == 'Asia']
df = df.drop(columns=['Entity', 'Population (historical)', 'Code']).reset_index(drop=True)
df["Global Annual Population (billions)"] /= 1e9
df.head()

   Year  Global Annual Population (billions)
0  1920                             1.896695
1  1921                             1.912087
2  1922                             1.928252
3  1923                             1.945106
4  1924                             1.962229

In [4]:
df.to_csv('cleaned_global_annual_population.csv', index=False)