In [12]:
import pandas as pd

In [13]:
df = pd.read_csv('annual-co-emissions.csv')
df.head()

        Entity  Year  Annual CO₂ emissions
0  Afghanistan  1949               14656.0
1  Afghanistan  1950               84272.0
2  Afghanistan  1951               91600.0
3  Afghanistan  1952               91600.0
4  Afghanistan  1953              106256.0

In [14]:
df = df[df['Entity'].isin(['Asia', 'Europe', 'Africa', 'Oceania', 'North America', 'South America'])]
df = df[(df['Year'] <= 2023) & (df['Year'] >= 1920)]
global_co2 = df.groupby("Year")["Annual CO₂ emissions"].sum()

df["Global Annual CO2 Emissions (billion t)"] = df["Year"].map(global_co2)
df = df[df['Entity'] == 'Asia']
df = df.drop(columns=['Entity', 'Annual CO₂ emissions']).reset_index(drop=True)
df['Global Annual CO2 Emissions (billion t)'] /= 1e9
df.head()

   Year  Global Annual CO2 Emissions (billion t)
0  1920                                 3.537837
1  1921                                 3.106184
2  1922                                 3.254463
3  1923                                 3.690698
4  1924                                 3.702777

In [15]:
df.to_csv('cleaned_global_annual_co2_emission.csv', index=False)